/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/_shop'
import { Route as ShopIndexRouteImport } from './routes/_shop/index'
import { Route as ShopProductsIndexRouteImport } from './routes/_shop/products/index'
import { Route as ShopProductsSlugRouteImport } from './routes/_shop/products/$slug'

const ShopRoute = ShopRouteImport.update({
  id: '/_shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopProductsIndexRoute = ShopProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopProductsSlugRoute = ShopProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => ShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShopIndexRoute
  '/products/$slug': typeof ShopProductsSlugRoute
  '/products/': typeof ShopProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ShopIndexRoute
  '/products/$slug': typeof ShopProductsSlugRoute
  '/products': typeof ShopProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shop': typeof ShopRouteWithChildren
  '/_shop/': typeof ShopIndexRoute
  '/_shop/products/$slug': typeof ShopProductsSlugRoute
  '/_shop/products/': typeof ShopProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/products/$slug' | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/products/$slug' | '/products'
  id:
    | '__root__'
    | '/_shop'
    | '/_shop/'
    | '/_shop/products/$slug'
    | '/_shop/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShopRoute: typeof ShopRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shop': {
      id: '/_shop'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shop/': {
      id: '/_shop/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/products/': {
      id: '/_shop/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ShopProductsIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/products/$slug': {
      id: '/_shop/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ShopProductsSlugRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface ShopRouteChildren {
  ShopIndexRoute: typeof ShopIndexRoute
  ShopProductsSlugRoute: typeof ShopProductsSlugRoute
  ShopProductsIndexRoute: typeof ShopProductsIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopIndexRoute: ShopIndexRoute,
  ShopProductsSlugRoute: ShopProductsSlugRoute,
  ShopProductsIndexRoute: ShopProductsIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShopRoute: ShopRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
