/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ShopRouteImport } from './routes/_shop'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ShopIndexRouteImport } from './routes/_shop/index'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminRecoveryRouteImport } from './routes/admin/recovery'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminIncompleteRouteImport } from './routes/admin/incomplete'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminCouponsRouteImport } from './routes/admin/coupons'
import { Route as AdminChatRouteImport } from './routes/admin/chat'
import { Route as AdminBrandsRouteImport } from './routes/admin/brands'
import { Route as ShopTrackRouteImport } from './routes/_shop/track'
import { Route as ShopMyReviewsRouteImport } from './routes/_shop/my-reviews'
import { Route as ShopLoginRouteImport } from './routes/_shop/login'
import { Route as ShopContactRouteImport } from './routes/_shop/contact'
import { Route as ShopCheckoutRouteImport } from './routes/_shop/checkout'
import { Route as ShopCartRouteImport } from './routes/_shop/cart'
import { Route as ShopAccountRouteImport } from './routes/_shop/account'
import { Route as ShopAboutRouteImport } from './routes/_shop/about'
import { Route as ShopProductsIndexRouteImport } from './routes/_shop/products/index'
import { Route as ApiPublicFbCapiRouteImport } from './routes/api/public/fb-capi'
import { Route as ShopProductsSlugRouteImport } from './routes/_shop/products/$slug'
import { Route as ShopPolicyRefundRouteImport } from './routes/_shop/policy/refund'
import { Route as ShopPolicyPrivacyRouteImport } from './routes/_shop/policy/privacy'
import { Route as ShopOrderIdRouteImport } from './routes/_shop/order/$id'
import { Route as ApiPublicUddoktapayCallbackRouteImport } from './routes/api/public/uddoktapay/callback'
import { Route as ApiPublicSteadfastSyncRouteImport } from './routes/api/public/steadfast/sync'
import { Route as ApiPaymentUddoktapayCreateRouteImport } from './routes/api/payment/uddoktapay/create'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/_shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecoveryRoute = AdminRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIncompleteRoute = AdminIncompleteRouteImport.update({
  id: '/incomplete',
  path: '/incomplete',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrandsRoute = AdminBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AdminRoute,
} as any)
const ShopTrackRoute = ShopTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => ShopRoute,
} as any)
const ShopMyReviewsRoute = ShopMyReviewsRouteImport.update({
  id: '/my-reviews',
  path: '/my-reviews',
  getParentRoute: () => ShopRoute,
} as any)
const ShopLoginRoute = ShopLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ShopRoute,
} as any)
const ShopContactRoute = ShopContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCheckoutRoute = ShopCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAccountRoute = ShopAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAboutRoute = ShopAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ShopRoute,
} as any)
const ShopProductsIndexRoute = ShopProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => ShopRoute,
} as any)
const ApiPublicFbCapiRoute = ApiPublicFbCapiRouteImport.update({
  id: '/api/public/fb-capi',
  path: '/api/public/fb-capi',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopProductsSlugRoute = ShopProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const ShopPolicyRefundRoute = ShopPolicyRefundRouteImport.update({
  id: '/policy/refund',
  path: '/policy/refund',
  getParentRoute: () => ShopRoute,
} as any)
const ShopPolicyPrivacyRoute = ShopPolicyPrivacyRouteImport.update({
  id: '/policy/privacy',
  path: '/policy/privacy',
  getParentRoute: () => ShopRoute,
} as any)
const ShopOrderIdRoute = ShopOrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => ShopRoute,
} as any)
const ApiPublicUddoktapayCallbackRoute =
  ApiPublicUddoktapayCallbackRouteImport.update({
    id: '/api/public/uddoktapay/callback',
    path: '/api/public/uddoktapay/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSteadfastSyncRoute = ApiPublicSteadfastSyncRouteImport.update({
  id: '/api/public/steadfast/sync',
  path: '/api/public/steadfast/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentUddoktapayCreateRoute =
  ApiPaymentUddoktapayCreateRouteImport.update({
    id: '/api/payment/uddoktapay/create',
    path: '/api/payment/uddoktapay/create',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShopIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/about': typeof ShopAboutRoute
  '/account': typeof ShopAccountRoute
  '/cart': typeof ShopCartRoute
  '/checkout': typeof ShopCheckoutRoute
  '/contact': typeof ShopContactRoute
  '/login': typeof ShopLoginRoute
  '/my-reviews': typeof ShopMyReviewsRoute
  '/track': typeof ShopTrackRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/incomplete': typeof AdminIncompleteRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/recovery': typeof AdminRecoveryRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/order/$id': typeof ShopOrderIdRoute
  '/policy/privacy': typeof ShopPolicyPrivacyRoute
  '/policy/refund': typeof ShopPolicyRefundRoute
  '/products/$slug': typeof ShopProductsSlugRoute
  '/api/public/fb-capi': typeof ApiPublicFbCapiRoute
  '/products/': typeof ShopProductsIndexRoute
  '/api/payment/uddoktapay/create': typeof ApiPaymentUddoktapayCreateRoute
  '/api/public/steadfast/sync': typeof ApiPublicSteadfastSyncRoute
  '/api/public/uddoktapay/callback': typeof ApiPublicUddoktapayCallbackRoute
}
export interface FileRoutesByTo {
  '/about': typeof ShopAboutRoute
  '/account': typeof ShopAccountRoute
  '/cart': typeof ShopCartRoute
  '/checkout': typeof ShopCheckoutRoute
  '/contact': typeof ShopContactRoute
  '/login': typeof ShopLoginRoute
  '/my-reviews': typeof ShopMyReviewsRoute
  '/track': typeof ShopTrackRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/incomplete': typeof AdminIncompleteRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/recovery': typeof AdminRecoveryRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/': typeof ShopIndexRoute
  '/admin': typeof AdminIndexRoute
  '/order/$id': typeof ShopOrderIdRoute
  '/policy/privacy': typeof ShopPolicyPrivacyRoute
  '/policy/refund': typeof ShopPolicyRefundRoute
  '/products/$slug': typeof ShopProductsSlugRoute
  '/api/public/fb-capi': typeof ApiPublicFbCapiRoute
  '/products': typeof ShopProductsIndexRoute
  '/api/payment/uddoktapay/create': typeof ApiPaymentUddoktapayCreateRoute
  '/api/public/steadfast/sync': typeof ApiPublicSteadfastSyncRoute
  '/api/public/uddoktapay/callback': typeof ApiPublicUddoktapayCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shop': typeof ShopRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_shop/about': typeof ShopAboutRoute
  '/_shop/account': typeof ShopAccountRoute
  '/_shop/cart': typeof ShopCartRoute
  '/_shop/checkout': typeof ShopCheckoutRoute
  '/_shop/contact': typeof ShopContactRoute
  '/_shop/login': typeof ShopLoginRoute
  '/_shop/my-reviews': typeof ShopMyReviewsRoute
  '/_shop/track': typeof ShopTrackRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/incomplete': typeof AdminIncompleteRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/recovery': typeof AdminRecoveryRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/_shop/': typeof ShopIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_shop/order/$id': typeof ShopOrderIdRoute
  '/_shop/policy/privacy': typeof ShopPolicyPrivacyRoute
  '/_shop/policy/refund': typeof ShopPolicyRefundRoute
  '/_shop/products/$slug': typeof ShopProductsSlugRoute
  '/api/public/fb-capi': typeof ApiPublicFbCapiRoute
  '/_shop/products/': typeof ShopProductsIndexRoute
  '/api/payment/uddoktapay/create': typeof ApiPaymentUddoktapayCreateRoute
  '/api/public/steadfast/sync': typeof ApiPublicSteadfastSyncRoute
  '/api/public/uddoktapay/callback': typeof ApiPublicUddoktapayCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/my-reviews'
    | '/track'
    | '/admin/brands'
    | '/admin/chat'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/incomplete'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/recovery'
    | '/admin/settings'
    | '/admin/'
    | '/order/$id'
    | '/policy/privacy'
    | '/policy/refund'
    | '/products/$slug'
    | '/api/public/fb-capi'
    | '/products/'
    | '/api/payment/uddoktapay/create'
    | '/api/public/steadfast/sync'
    | '/api/public/uddoktapay/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/my-reviews'
    | '/track'
    | '/admin/brands'
    | '/admin/chat'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/incomplete'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/recovery'
    | '/admin/settings'
    | '/'
    | '/admin'
    | '/order/$id'
    | '/policy/privacy'
    | '/policy/refund'
    | '/products/$slug'
    | '/api/public/fb-capi'
    | '/products'
    | '/api/payment/uddoktapay/create'
    | '/api/public/steadfast/sync'
    | '/api/public/uddoktapay/callback'
  id:
    | '__root__'
    | '/_shop'
    | '/admin'
    | '/_shop/about'
    | '/_shop/account'
    | '/_shop/cart'
    | '/_shop/checkout'
    | '/_shop/contact'
    | '/_shop/login'
    | '/_shop/my-reviews'
    | '/_shop/track'
    | '/admin/brands'
    | '/admin/chat'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/incomplete'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/recovery'
    | '/admin/settings'
    | '/_shop/'
    | '/admin/'
    | '/_shop/order/$id'
    | '/_shop/policy/privacy'
    | '/_shop/policy/refund'
    | '/_shop/products/$slug'
    | '/api/public/fb-capi'
    | '/_shop/products/'
    | '/api/payment/uddoktapay/create'
    | '/api/public/steadfast/sync'
    | '/api/public/uddoktapay/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShopRoute: typeof ShopRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ApiPublicFbCapiRoute: typeof ApiPublicFbCapiRoute
  ApiPaymentUddoktapayCreateRoute: typeof ApiPaymentUddoktapayCreateRoute
  ApiPublicSteadfastSyncRoute: typeof ApiPublicSteadfastSyncRoute
  ApiPublicUddoktapayCallbackRoute: typeof ApiPublicUddoktapayCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shop': {
      id: '/_shop'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_shop/': {
      id: '/_shop/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recovery': {
      id: '/admin/recovery'
      path: '/recovery'
      fullPath: '/admin/recovery'
      preLoaderRoute: typeof AdminRecoveryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/incomplete': {
      id: '/admin/incomplete'
      path: '/incomplete'
      fullPath: '/admin/incomplete'
      preLoaderRoute: typeof AdminIncompleteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/brands': {
      id: '/admin/brands'
      path: '/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AdminBrandsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_shop/track': {
      id: '/_shop/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof ShopTrackRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/my-reviews': {
      id: '/_shop/my-reviews'
      path: '/my-reviews'
      fullPath: '/my-reviews'
      preLoaderRoute: typeof ShopMyReviewsRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/login': {
      id: '/_shop/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof ShopLoginRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/contact': {
      id: '/_shop/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ShopContactRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/checkout': {
      id: '/_shop/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof ShopCheckoutRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/cart': {
      id: '/_shop/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/account': {
      id: '/_shop/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ShopAccountRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/about': {
      id: '/_shop/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof ShopAboutRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/products/': {
      id: '/_shop/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ShopProductsIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/api/public/fb-capi': {
      id: '/api/public/fb-capi'
      path: '/api/public/fb-capi'
      fullPath: '/api/public/fb-capi'
      preLoaderRoute: typeof ApiPublicFbCapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shop/products/$slug': {
      id: '/_shop/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ShopProductsSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/policy/refund': {
      id: '/_shop/policy/refund'
      path: '/policy/refund'
      fullPath: '/policy/refund'
      preLoaderRoute: typeof ShopPolicyRefundRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/policy/privacy': {
      id: '/_shop/policy/privacy'
      path: '/policy/privacy'
      fullPath: '/policy/privacy'
      preLoaderRoute: typeof ShopPolicyPrivacyRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/order/$id': {
      id: '/_shop/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof ShopOrderIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/api/public/uddoktapay/callback': {
      id: '/api/public/uddoktapay/callback'
      path: '/api/public/uddoktapay/callback'
      fullPath: '/api/public/uddoktapay/callback'
      preLoaderRoute: typeof ApiPublicUddoktapayCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/steadfast/sync': {
      id: '/api/public/steadfast/sync'
      path: '/api/public/steadfast/sync'
      fullPath: '/api/public/steadfast/sync'
      preLoaderRoute: typeof ApiPublicSteadfastSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/uddoktapay/create': {
      id: '/api/payment/uddoktapay/create'
      path: '/api/payment/uddoktapay/create'
      fullPath: '/api/payment/uddoktapay/create'
      preLoaderRoute: typeof ApiPaymentUddoktapayCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShopRouteChildren {
  ShopAboutRoute: typeof ShopAboutRoute
  ShopAccountRoute: typeof ShopAccountRoute
  ShopCartRoute: typeof ShopCartRoute
  ShopCheckoutRoute: typeof ShopCheckoutRoute
  ShopContactRoute: typeof ShopContactRoute
  ShopLoginRoute: typeof ShopLoginRoute
  ShopMyReviewsRoute: typeof ShopMyReviewsRoute
  ShopTrackRoute: typeof ShopTrackRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopOrderIdRoute: typeof ShopOrderIdRoute
  ShopPolicyPrivacyRoute: typeof ShopPolicyPrivacyRoute
  ShopPolicyRefundRoute: typeof ShopPolicyRefundRoute
  ShopProductsSlugRoute: typeof ShopProductsSlugRoute
  ShopProductsIndexRoute: typeof ShopProductsIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopAboutRoute: ShopAboutRoute,
  ShopAccountRoute: ShopAccountRoute,
  ShopCartRoute: ShopCartRoute,
  ShopCheckoutRoute: ShopCheckoutRoute,
  ShopContactRoute: ShopContactRoute,
  ShopLoginRoute: ShopLoginRoute,
  ShopMyReviewsRoute: ShopMyReviewsRoute,
  ShopTrackRoute: ShopTrackRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopOrderIdRoute: ShopOrderIdRoute,
  ShopPolicyPrivacyRoute: ShopPolicyPrivacyRoute,
  ShopPolicyRefundRoute: ShopPolicyRefundRoute,
  ShopProductsSlugRoute: ShopProductsSlugRoute,
  ShopProductsIndexRoute: ShopProductsIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

interface AdminRouteChildren {
  AdminBrandsRoute: typeof AdminBrandsRoute
  AdminChatRoute: typeof AdminChatRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminIncompleteRoute: typeof AdminIncompleteRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminRecoveryRoute: typeof AdminRecoveryRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBrandsRoute: AdminBrandsRoute,
  AdminChatRoute: AdminChatRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminIncompleteRoute: AdminIncompleteRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminRecoveryRoute: AdminRecoveryRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShopRoute: ShopRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ApiPublicFbCapiRoute: ApiPublicFbCapiRoute,
  ApiPaymentUddoktapayCreateRoute: ApiPaymentUddoktapayCreateRoute,
  ApiPublicSteadfastSyncRoute: ApiPublicSteadfastSyncRoute,
  ApiPublicUddoktapayCallbackRoute: ApiPublicUddoktapayCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
